In [1]:
%%capture
%pip install -U transformers
#%pip install torch
%pip install -U peft
%pip install -i https://pypi.org/simple/ bitsandbytes
%pip install -U accelerate
%pip install -U trl
%pip install datasets==2.16.0

In [2]:
from warnings import filterwarnings
filterwarnings('ignore')
import json
import re
import wandb
import os
import unicodedata
from pprint import pprint
import pandas as pd
import torch
from kaggle_secrets import UserSecretsClient
from datasets import Dataset, load_dataset
from huggingface_hub import notebook_login, login
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, PeftModel
from trl import SFTTrainer

2024-04-24 15:27:51.530432: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-24 15:27:51.530568: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-24 15:27:51.653461: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [3]:
df = pd.read_csv("/kaggle/input/vietnamese-news-data/Dataset_articles.csv", nrows=5000)
df.head()

,Unnamed: 0,URL,Title,Summary,Contents,Date,Author(s),Category,Tags
0,0,https://laodong.vn/bat-dong-san/thong-tin-ngoc...,"Thông tin “Ngọc Trinh mua đất ở Bảo Lộc"" chỉ l...","Lâm Đồng - Lãnh đạo thành phố Bảo Lộc, Lâm Đồn...","Những ngày vừa qua, trên trang Facebook chính ...","Thứ sáu, 20/05/2022 08:56 (GMT+7)",Phương Nhiên,Bất động sản,"['Lâm Đồng', 'Ngọc Trinh', 'Chiêu trò', 'Giá đ..."
1,1,https://laodong.vn/bat-dong-san/lo-hong-trong-...,Lỗ hổng trong việc thẩm tra năng lực tài chính...,TPHCM - Việc không thể cưỡng chế thuế của hai ...,"Theo thông tin từ Cục Thuế TP.HCM, hiện cơ qua...","Thứ sáu, 20/05/2022 08:10 (GMT+7)",Gia Miêu,Bất động sản,"['Thủ Thiêm', 'Đấu giá đất']"
2,2,https://laodong.vn/bat-dong-san/som-hoan-thien...,Sớm hoàn thiện các dự án nhà ở xã hội để CNLĐ ...,"Hiện trên địa bàn tỉnh Ninh Bình có 32 khu, cụ...",CNLĐ mong muốn sớm được tiếp cận với nhà ở xã ...,"Thứ sáu, 20/05/2022 07:47 (GMT+7)",NGUYỄN TRƯỜNG,Bất động sản,"['Dự án', 'Nhà ở xã hội', 'Dự án nhà ở xã hội'..."
3,3,https://laodong.vn/bat-dong-san/chi-tiet-ho-so...,Chi tiết hồ sơ hoàn công nhà ở năm 2022,Hoàn công nhà ở với ý nghĩa là điều kiện để đư...,Hoàn công nhà ở là một thủ tục hành chính tron...,"Thứ sáu, 20/05/2022 06:44 (GMT+7)",Kim Nhung (T/H),Bất động sản,"['Giấy phép xây dựng', 'Hồ sơ hoàn công', 'nhà..."
4,4,https://laodong.vn/bat-dong-san/khoi-tao-khong...,"Khởi tạo không gian sống đẳng cấp, đón sóng đầ...",Có rất nhiều lý do khiến những dự án thấp nội ...,Đi dọc đường Lê Văn Lương kéo dài xuống khu Dư...,"Thứ năm, 19/05/2022 15:30 (GMT+7)",Huyền Nguyễn,Bất động sản,['An Quý Villa']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   URL         5000 non-null   object
 2   Title       5000 non-null   object
 3   Summary     5000 non-null   object
 4   Contents    4918 non-null   object
 5   Date        5000 non-null   object
 6   Author(s)   5000 non-null   object
 7   Category    5000 non-null   object
 8   Tags        5000 non-null   object
dtypes: int64(1), object(8)
memory usage: 351.7+ KB

In [5]:
df.dropna(inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4918 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4918 non-null   int64
 1   URL         4918 non-null   object
 2   Title       4918 non-null   object
 3   Summary     4918 non-null   object
 4   Contents    4918 non-null   object
 5   Date        4918 non-null   object
 6   Author(s)   4918 non-null   object
 7   Category    4918 non-null   object
 8   Tags        4918 non-null   object
dtypes: int64(1), object(8)
memory usage: 384.2+ KB

In [7]:
df[['Category']].stack().unique()

array(['Bất động sản', 'Xã hội', 'Lao Động cuối tuần', 'Kinh doanh',
       'Thời sự', 'Công đoàn', 'Bạn đọc', 'Pháp luật'], dtype=object)

In [8]:
len(df)

4918

In [9]:
print(df['Summary'].to_list()[0])

Lâm Đồng - Lãnh đạo thành phố Bảo Lộc, Lâm Đồng khẳng định thông tin người mẫu Ngọc Trinh mua 11ha đất ở địa phương để làm homestay là hoàn toàn sai sự thật. Đó chỉ là chiêu trò của giới bất động sản để thổi giá đất.

In [10]:
df1 = df[['Summary', 'Contents']]

In [11]:
df1.iloc[0]["Summary"], df1.iloc[0]["Contents"]

('Lâm\xa0Đồng -\xa0Lãnh đạo thành phố Bảo Lộc, Lâm Đồng\xa0khẳng định thông\xa0tin\xa0người mẫu Ngọc Trinh mua 11ha đất ở địa phương để làm homestay là\xa0hoàn toàn sai sự thật.\xa0Đó\xa0chỉ là chiêu trò của\xa0giới bất động sản\xa0để thổi giá đất.',
 'Những ngày\xa0vừa\xa0qua, trên\xa0trang Facebook chính chủ của Ngọc Trinh có đăng tải thông tin người mẫu này vừa mua\xa011ha đất với homestay\xa0tại xã Đại Lào, TP.Bảo Lộc, thu hút sự chú ý lớn từ đông đảo cộng đồng mạng.\xa0 Sau\xa0đó, một số trang thông tin và mạng\xa0xã hội khác tiếp tục đăng tại lại thông tin này,\xa0đồng thời khẳng định, khu đất Ngọc Trinh mới mua nằm tại xã Đại Lào, TP.Bảo Lộc,\xa0tọa lạc ở vị trí đắc địa, tiếp giáp núi và có khí hậu mát mẻ dễ chịu, thích hợp cho kỳ nghỉ trốn nắng hè cho du khách. Trước\xa0thông tin này, ông Đoàn Kim Đình - Chủ tịch UBND thành phố Bảo Lộc cho\xa0biết,\xa0UBND thành phố đã yêu cầu cơ quan chức năng và UBND xã Đại Lào phối hợp kiểm chứng thông tin. Qua xác minh,\xa0khu đất Ngọc Trinh chụp hình và\xa0đăng tải lên mạng xã hội\xa0thuộc hẻm 61 B’Lao Srê,\xa0xã Đại Lào. Nhưng đây không phải là đất xây dựng homestay của Ngọc Trinh. Trong các hồ sơ thủ tục liên quan đất đai trên địa bàn xã Đại Lào không có chủ nhân nào tên là Trần Thị Ngọc Trinh (tên thật\xa0của\xa0Ngọc Trinh).\xa0 Mặt khác tất cả các dự án xây dựng homestay nghỉ dưỡng trên địa bàn thành phố Bảo Lộc đều được địa phương cấp phép và quản lý, trong các dự án đã triển khai và đang chờ phê duyệt không có dự án nào có chủ dự án tên Ngọc Trinh. Đại\xa0diện lãnh đạo UBND TP.Bảo Lộc cũng nói thêm,\xa0đây có thể là chiêu trò câu like của giới bất động sản. Việc này, khiến dư luận đánh giá sai về công tác quản lý đất đai, xây dựng của địa phương và cơ quan chức năng trên địa bàn thành phố Bảo Lộc; đồng thời, cũng là chiêu trò mà giới bất động sản hướng tới để thổi phồng giá đất.\xa0 Hiện tại, UBND thành phố Bảo Lộc đang chỉ đạo các ngành chức năng và UBND xã Đại Lào xác minh, nếu đây là chiêu trò câu like sai sự thật thì địa phương kiên quyết xử lý theo quy định. Người dân cũng cần hết sức cẩn thận, kiểm chứng kỹ càng để tránh bị dắt mũi bởi những thông tin được các cá nhân đăng tải tự do như thế này.')

In [12]:
dataset = Dataset.from_pandas(df1)
dataset

Dataset({
    features: ['Summary', 'Contents', '__index_level_0__'],
    num_rows: 4918
})

### Formatted Prompt

Bạn là một trợ lí Tiếng Việt nhiệt tình và trung thực. Hãy luôn trả lời một cách hữu ích nhất có thể, đồng thời giữ an toàn.
Câu trả lời của bạn không nên chứa bất kỳ nội dung gây hại, phân biệt chủng tộc, phân biệt giới tính, độc hại, nguy hiểm hoặc bất hợp pháp nào. Hãy đảm bảo rằng các câu trả lời của bạn không có thiên kiến xã hội và mang tính tích cực.Nếu một câu hỏi không có ý nghĩa hoặc không hợp lý về mặt thông tin, hãy giải thích tại sao thay vì trả lời một điều gì đó không chính xác. Nếu bạn không biết câu trả lời cho một câu hỏi, hãy trẳ lời là bạn không biết và vui lòng không chia sẻ thông tin sai lệch.


{prompt}

In [13]:
DEFAULT_SYSTEM_PROMPT = """
Bạn là một trợ lí Tiếng Việt nhiệt tình và trung thực. Hãy luôn trả lời một cách hữu ích nhất có thể, đồng thời giữ an toàn.
Câu trả lời của bạn không nên chứa bất kỳ nội dung gây hại, phân biệt chủng tộc, phân biệt giới tính, độc hại, nguy hiểm hoặc bất hợp pháp nào. 
Hãy đảm bảo rằng các câu trả lời của bạn không có thiên kiến xã hội và mang tính tích cực. Nếu một câu hỏi không có ý nghĩa hoặc không hợp lý về 
mặt thông tin, hãy giải thích tại sao thay vì trả lời một điều gì đó không chính xác. Nếu bạn không biết câu trả lời cho một câu hỏi, hãy trẳ lời 
là bạn không biết và vui lòng không chia sẻ thông tin sai lệch. 
Dưới đây là một tin tức. Bạn hãy viết một đoạn tóm tắt tin tức trên trong khoảng 100 từ. Hãy tóm tắt nội dung chính, quan trọng của tin tức đó, 
đồng thời đoạn tóm tắt phải được viết lại rõ ràng, thông tin được viết lại hợp lý. 
 
"""

In [14]:
def generate_training_prompt(
    article: str, summary: str, system_prompt: str = DEFAULT_SYSTEM_PROMPT
) -> str:
    
    input_prefix = "<s>[INST] "
    input_suffix = "[/INST] "
    pre_prompt_prefix = "<s>[INST]  <<SYS>>\n"
    pre_prompt_suffix = "<</SYS>> \n\n"
    eos_token = "</s>"
    
    full_prompt = ""
    full_prompt += pre_prompt_prefix
    full_prompt += "\n" + system_prompt
    full_prompt += pre_prompt_suffix
    full_prompt += "\n" + article
    full_prompt += input_suffix
    full_prompt += "\n\n### Response:"
    full_prompt += "\n" + summary
    full_prompt += eos_token
    return full_prompt

In [15]:
# Split the processed dataset into train, validation, and test sets
train_dataset = dataset.shuffle(seed=21).select(range(0, int(0.8 * len(dataset))))
validation_dataset = dataset.shuffle(seed=21).select(range(int(0.8 * len(dataset)), int(0.9 * len(dataset))))
test_dataset = dataset.shuffle(seed=21).select(range(int(0.9 * len(dataset)), len(dataset)))

In [16]:
!pip install py-vncorenlp

Collecting py-vncorenlp
  Downloading py_vncorenlp-0.1.4.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... - \ done
Collecting pyjnius (from py-vncorenlp)
  Downloading pyjnius-1.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Downloading pyjnius-1.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 6.0 MB/s eta 0:00:00
Building wheels for collected packages: py-vncorenlp
  Building wheel for py-vncorenlp (setup.py) ... - \ | done
  Created wheel for py-vncorenlp: filename=py_vncorenlp-0.1.4-py3-none-any.whl size=4305 sha256=3d166a9d7a13482cf0838f82da35629326bff7b1f02d028b684f41d4353f4d2e
  Stored in directory: /root/.cache/pip/wheels/d5/d9/bf/62632cdb007c702a0664091e92a0bb1f18a2fcecbe962d9827
Successfully built py-vncorenlp
Installing collected packages: pyjnius, py-vncorenlp
Successfully installed py-vncorenlp-0.1.4 pyjnius-1.6.1

In [17]:
!sudo apt -y install default-jdk

The following additional packages will be installed:
  default-jdk-headless libice-dev libpthread-stubs0-dev libsm-dev libx11-dev
  libxau-dev libxcb1-dev libxdmcp-dev libxt-dev openjdk-11-jdk
  openjdk-11-jdk-headless x11proto-core-dev x11proto-dev xorg-sgml-doctools
  xtrans-dev
Suggested packages:
  libice-doc libsm-doc libx11-doc libxcb-doc libxt-doc openjdk-11-demo
  openjdk-11-source visualvm
The following NEW packages will be installed:
  default-jdk default-jdk-headless libice-dev libpthread-stubs0-dev libsm-dev
  libx11-dev libxau-dev libxcb1-dev libxdmcp-dev libxt-dev openjdk-11-jdk
  openjdk-11-jdk-headless x11proto-core-dev x11proto-dev xorg-sgml-doctools
  xtrans-dev
0 upgraded, 16 newly installed, 0 to remove and 65 not upgraded.
Need to get 76.9 MB of archives.
After this operation, 90.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.22+7-0ubuntu2~20.04.1 [73.7 MB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 default-jdk-headless amd64 2:1.11-72 [1140 B]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 openjdk-11-jdk amd64 11.0.22+7-0ubuntu2~20.04.1 [1338 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 default-jdk amd64 2:1.11-72 [1096 B]
Get:5 http://archive.ubuntu.com/ubuntu focal/main amd64 xorg-sgml-doctools all 1:1.11-1 [12.9 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 x11proto-dev all 2019.2-1ubuntu1 [594 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 x11proto-core-dev all 2019.2-1ubuntu1 [2620 B]
Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 libice-dev amd64 2:1.0.10-0ubuntu1 [47.8 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/main amd64 libpthread-stubs0-dev amd64 0.4-1 [5384 B]
Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 libsm-dev amd64 2:1.2.3-1 [17.0 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 libxau-dev amd64 1:1.0.9-0ubuntu1 [9552 B]
Get:12 http://archive.ubuntu.com/ubuntu focal/main amd64 libxdmcp-dev amd64 1:1.1.3-0ubuntu1 [25.3 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal/main amd64 xtrans-dev all 1.4.0-1 [68.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb1-dev amd64 1.14-2 [80.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libx11-dev amd64 2:1.6.9-2ubuntu1.6 [648 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal/main amd64 libxt-dev amd64 1:1.1.5-1 [395 kB]
Fetched 76.9 MB in 2s (43.9 MB/s)

78Selecting previously unselected package openjdk-11-jdk-headless:amd64.
(Reading database ... 113807 files and directories currently installed.)
Preparing to unpack .../00-openjdk-11-jdk-headless_11.0.22+7-0ubuntu2~20.04.1_amd64.deb ...
7Progress: [  0%] [..........................................................] 87Progress: [  2%] [..........................................................] 8Unpacking openjdk-11-jdk-headless:amd64 (11.0.22+7-0ubuntu2~20.04.1) ...
7Progress: [  3%] [#.........................................................] 8Selecting previously unselected package default-jdk-headless.
Preparing to unpack .../01-default-jdk-headless_2%3a1.11-72_amd64.deb ...
7Progress: [  5%] [##........................................................] 8Unpacking default-jdk-headless (2:1.11-72) ...
7Progress: [  6%] [###.......................................................] 8Selecting previously unselected package openjdk-11-jdk:amd64.
Preparing to unpack .../02-openjdk-11-jdk_11.0.22+7-0ubuntu2~20.04.1_amd64.deb ...
7Progress: [  8%] [####......................................................] 8Unpacking openjdk-11-jdk:amd64 (11.0.22+7-0ubuntu2~20.04.1) ...
7Progress: [  9%] [#####.....................................................] 8Selecting previously unselected package default-jdk.
Preparing to unpack .../03-default-jdk_2%3a1.11-72_amd64.deb ...
7Progress: [ 11%] [######....................................................] 8Unpacking default-jdk (2:1.11-72) ...
7Progress: [ 12%] [#######...................................................] 8Selecting previously unselected package xorg-sgml-doctools.
Preparing to unpack .../04-xorg-sgml-doctools_1%3a1.11-1_all.deb ...
7Progress: [ 14%] [########..................................................] 8Unpacking xorg-sgml-doctools (1:1.11-1) ...
7Progress: [ 15%] [########..................................................] 8Selecting previously unselected package x11proto-dev.
Preparing to unpack .../05-x11proto-dev_2019.2-1ubuntu1_all.deb ...
7Progress: [ 17%] [#########.................................................] 8Unpacking x11proto-dev (2019.2-1ubuntu1) ...
7Progress: [ 18%] [##########................................................] 8Selecting previously unselected package x11proto-core-dev.
Preparing to unpack .../06-x11proto-core-dev_2019.2-1ubuntu1_all.deb ...
7Progress: [ 20%] [###########...............................................] 8Unpacking x11proto-core-dev (2019.2-1ubuntu1) ...
7Progress: [ 22%] [############..............................................] 8Selecting previously unselected package libice-dev:amd64.
Preparing to unpack .../07-libice-dev_2%3a1.0.10-0ubuntu1_amd64.deb ...
7Progress: [ 23%] [#############.............................................] 8Unpacking libice-dev:amd64 (2:1.0.10-0ubuntu1) ...
7Progress: [ 25%] [##############............................................] 8Selecting previously unselected package libpthread-stubs0-dev:amd64.
Preparing to unpack .../08-libpthread-stubs0-dev_0.4-1_amd64.deb ...
7Progress: [ 26%] [###############...........................................] 8Unpacking libpthread-stubs0-dev:amd64 (0.4-1) ...
7Progress: [ 28%] [################..........................................] 8Selecting previously unselected package libsm-dev:amd64.
Preparing to unpack .../09-libsm-dev_2%3a1.2.3-1_amd64.deb ...
7Progress: [ 29%] [################..........................................] 8Unpacking libsm-dev:amd64 (2:1.2.3-1) ...
7Progress: [ 31%] [#################.........................................] 8Selecting previously unselected package libxau-dev:amd64.
Preparing to unpack .../10-libxau-dev_1%3a1.0.9-0ubuntu1_amd64.deb ...
7Progress: [ 32%] [##################........................................] 8Unpacking libxau-dev:amd64 (1:1.0.9-0ubuntu1) ...
7Progress: [ 34%] [###################.......................................] 8Selecting previously unselected package libxdmcp-dev:amd64.
Preparing to unpack .../11-libxdmcp-dev_1%3a1.1.3-0ubuntu1_amd64.deb ...
7Progress: [ 35%] [####################......................................] 8Unpacking libxdmcp-dev:amd64 (1:1.1.3-0ubuntu1) ...
7Progress: [ 37%] [#####################.....................................] 8Selecting previously unselected package xtrans-dev.
Preparing to unpack .../12-xtrans-dev_1.4.0-1_all.deb ...
7Progress: [ 38%] [######################....................................] 8Unpacking xtrans-dev (1.4.0-1) ...
7Progress: [ 40%] [#######################...................................] 8Selecting previously unselected package libxcb1-dev:amd64.
Preparing to unpack .../13-libxcb1-dev_1.14-2_amd64.deb ...
7Progress: [ 42%] [########################..................................] 8Unpacking libxcb1-dev:amd64 (1.14-2) ...
7Progress: [ 43%] [########################..................................] 8Selecting previously unselected package libx11-dev:amd64.
Preparing to unpack .../14-libx11-dev_2%3a1.6.9-2ubuntu1.6_amd64.deb ...
7Progress: [ 45%] [#########################.................................] 8Unpacking libx11-dev:amd64 (2:1.6.9-2ubuntu1.6) ...
7Progress: [ 46%] [##########################................................] 8Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../15-libxt-dev_1%3a1.1.5-1_amd64.deb ...
7Progress: [ 48%] [###########################...............................] 8Unpacking libxt-dev:amd64 (1:1.1.5-1) ...
7Progress: [ 49%] [############################..............................] 8Setting up openjdk-11-jdk-headless:amd64 (11.0.22+7-0ubuntu2~20.04.1) ...
7Progress: [ 51%] [#############################.............................] 8update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdeprscan to provide /usr/bin/jdeprscan (jdeprscan) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jimage to provide /usr/bin/jimage (jimage) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jlink to provide /usr/bin/jlink (jlink) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jmod to provide /usr/bin/jmod (jmod) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jps to provide /usr/bin/jps (jps) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jshell to provide /usr/bin/jshell (jshell) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jhsdb to provide /usr/bin/jhsdb (jhsdb) in auto mode
7Progress: [ 52%] [##############################............................] 8Setting up libpthread-stubs0-dev:amd64 (0.4-1) ...
7Progress: [ 54%] [###############################...........................] 87Progress: [ 55%] [################################..........................] 8Setting up xtrans-dev (1.4.0-1) ...
7Progress: [ 57%] [#################################.........................] 87Progress: [ 58%] [#################################.........................] 8Setting up default-jdk-headless (2:1.11-72) ...
7Progress: [ 60%] [##################################........................] 87Progress: [ 62%] [###################################.......................] 8Setting up openjdk-11-jdk:amd64 (11.0.22+7-0ubuntu2~20.04.1) ...
7Progress: [ 63%] [####################################......................] 8update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
7Progress: [ 65%] [#####################################.....................] 8Setting up xorg-sgml-doctools (1:1.11-1) ...
7Progress: [ 66%] [######################################....................] 87Progress: [ 68%] [#######################################...................] 8Setting up x11proto-dev (2019.2-1ubuntu1) ...
7Progress: [ 69%] [########################################..................] 87Progress: [ 71%] [#########################################.................] 8Setting up libxau-dev:amd64 (1:1.0.9-0ubuntu1) ...
7Progress: [ 72%] [#########################################.................] 87Progress: [ 74%] [##########################################................] 8Setting up libice-dev:amd64 (2:1.0.10-0ubuntu1) ...
7Progress: [ 75%] [###########################################...............] 87Progress: [ 77%] [############################################..............] 8Setting up libsm-dev:amd64 (2:1.2.3-1) ...
7Progress: [ 78%] [#############################################.............] 87Progress: [ 80%] [##############################################............] 8Setting up default-jdk (2:1.11-72) ...
7Progress: [ 82%] [###############################################...........] 87Progress: [ 83%] [################################################..........] 8Setting up libxdmcp-dev:amd64 (1:1.1.3-0ubuntu1) ...
7Progress: [ 85%] [#################################################.........] 87Progress: [ 86%] [#################################################.........] 8Setting up x11proto-core-dev (2019.2-1ubuntu1) ...
7Progress: [ 88%] [##################################################........] 87Progress: [ 89%] [###################################################.......] 8Setting up libxcb1-dev:amd64 (1.14-2) ...
7Progress: [ 91%] [####################################################......] 87Progress: [ 92%] [#####################################################.....] 8Setting up libx11-dev:amd64 (2:1.6.9-2ubuntu1.6) ...
7Progress: [ 94%] [######################################################....] 87Progress: [ 95%] [#######################################################...] 8Setting up libxt-dev:amd64 (1:1.1.5-1) ...
7Progress: [ 97%] [########################################################..] 87Progress: [ 98%] [#########################################################.] 8Processing triggers for man-db (2.9.1-1) ...

78

In [18]:
!javac -version

javac 11.0.22

In [19]:
import py_vncorenlp
py_vncorenlp.download_model(save_dir='/kaggle/working/')

--2024-04-24 15:28:32--  https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.2.jar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27412703 (26M) [application/octet-stream]
Saving to: 'VnCoreNLP-1.2.jar'

     0K .......... .......... .......... .......... ..........  0% 2.38M 11s
    50K .......... .......... .......... .......... ..........  0% 13.8M 6s
   100K .......... .......... .......... .......... ..........  0% 6.55M 6s
   150K .......... .......... .......... .......... ..........  0% 23.8M 4s
   200K .......... .......... .......... .......... ..........  0% 23.1M 4s
   250K .......... .......... .......... .......... ..........  1% 41.7M 3s
   300K .......... .......... .......... .......... ..........  1% 9.28M 3s
   350K .......... .......... .......... .......... ..........  1% 23.3M 3s
   400K .......... .......... .......... .......... ..........  1% 78.2M 3s
   450K .......... .......... .......... .......... ..........  1% 40.2M 2s
   500K .......... .......... .......... .......... ..........  2% 57.7M 2s
   550K .......... .......... .......... .......... ..........  2% 93.6M 2s
   600K .......... .......... .......... .......... ..........  2% 11.0M 2s
   650K .......... .......... .......... .......... ..........  2% 37.1M 2s
   700K .......... .......... .......... .......... ..........  2% 46.5M 2s
   750K .......... .......... .......... .......... ..........  2%  156M 2s
   800K .......... .......... .......... .......... ..........  3%  103M 2s
   850K .......... .......... .......... .......... ..........  3% 93.8M 2s
   900K .......... .......... .......... .......... ..........  3% 86.3M 2s
   950K .......... .......... .......... .......... ..........  3%  160M 1s
  1000K .......... .......... .......... .......... ..........  3%  104M 1s
  1050K .......... .......... .......... .......... ..........  4% 73.0M 1s
  1100K .......... .......... .......... .......... ..........  4%  127M 1s
  1150K .......... .......... .......... .......... ..........  4%  127M 1s
  1200K .......... .......... .......... .......... ..........  4%  123M 1s
  1250K .......... .......... .......... .......... ..........  4% 13.4M 1s
  1300K .......... .......... .......... .......... ..........  5% 68.1M 1s
  1350K .......... .......... .......... .......... ..........  5% 83.7M 1s
  1400K .......... .......... .......... .......... ..........  5%  163M 1s
  1450K .......... .......... .......... .......... ..........  5%  244M 1s
  1500K .......... .......... .......... .......... ..........  5% 65.7M 1s
  1550K .......... .......... .......... .......... ..........  5%  159M 1s
  1600K .......... .......... .......... .......... ..........  6%  229M 1s
  1650K .......... .......... .......... .......... ..........  6%  264M 1s
  1700K .......... .......... .......... .......... ..........  6%  232M 1s
  1750K .......... .......... .......... .......... ..........  6%  119M 1s
  1800K .......... .......... .......... .......... ..........  6%  217M 1s
  1850K .......... .......... .......... .......... ..........  7%  195M 1s
  1900K .......... .......... .......... .......... ..........  7%  143M 1s
  1950K .......... .......... .......... .......... ..........  7%  126M 1s
  2000K .......... .......... .......... .......... ..........  7%  147M 1s
  2050K .......... .......... .......... .......... ..........  7%  143M 1s
  2100K .......... .......... .......... .......... ..........  8%  152M 1s
  2150K .......... .......... .......... .......... ..........  8%  118M 1s
  2200K .......... .......... .......... .......... ..........  8%  157M 1s
  2250K .......... .......... .......... .......... ..........  8%  158M 1s
  2300K .......... .......... .......... .......... ..........  8%  165M 1s
  2350K .......... .......... .......... .......... ..........  8%  150M 1s
  2400K .......... .......... .......... .......... ..........  9%  170M 1s
  2450K .......... .......... .......... .......... ..........  9%  161M 1s
  2500K .......... .......... .......... .......... ..........  9% 25.7M 1s
  2550K .......... .......... .......... .......... ..........  9%  137M 1s
  2600K .......... .......... .......... .......... ..........  9%  108M 1s
  2650K .......... .......... .......... .......... .......... 10%  175M 1s
  2700K .......... .......... .......... .......... .......... 10%  157M 1s
  2750K .......... .......... .......... .......... .......... 10%  112M 1s
  2800K .......... .......... .......... .......... .......... 10%  146M 1s
  2850K .......... .......... .......... .......... .......... 10%  168M 1s
  2900K .......... .......... .......... .......... .......... 11%  171M 1s
  2950K .......... .......... .......... .......... .......... 11%  106M 1s
  3000K .......... .......... .......... .......... .......... 11%  133M 1s
  3050K .......... .......... .......... .......... .......... 11%  140M 1s
  3100K .......... .......... .......... .......... .......... 11%  132M 1s
  3150K .......... .......... .......... .......... .......... 11%  120M 1s
  3200K .......... .......... .......... .......... .......... 12%  138M 1s
  3250K .......... .......... .......... .......... .......... 12%  131M 1s
  3300K .......... .......... .......... .......... .......... 12%  138M 1s
  3350K .......... .......... .......... .......... .......... 12%  106M 1s
  3400K .......... .......... .......... .......... .......... 12%  142M 1s
  3450K .......... .......... .......... .......... .......... 13%  136M 1s
  3500K .......... .......... .......... .......... .......... 13%  132M 1s
  3550K .......... .......... .......... .......... .......... 13%  126M 1s
  3600K .......... .......... .......... .......... .......... 13%  149M 1s
  3650K .......... .......... .......... .......... .......... 13%  154M 1s
  3700K .......... .......... .......... .......... .......... 14%  140M 0s
  3750K .......... .......... .......... .......... .......... 14%  160M 0s
  3800K .......... .......... .......... .......... .......... 14%  160M 0s
  3850K .......... .......... .......... .......... .......... 14%  164M 0s
  3900K .......... .......... .......... .......... .......... 14%  143M 0s
  3950K .......... .......... .......... .......... .......... 14%  145M 0s
  4000K .......... .......... .......... .......... .......... 15%  136M 0s
  4050K .......... .......... .......... .......... .......... 15%  145M 0s
  4100K .......... .......... .......... .......... .......... 15%  154M 0s
  4150K .......... .......... .......... .......... .......... 15%  143M 0s
  4200K .......... .......... .......... .......... .......... 15%  129M 0s
  4250K .......... .......... .......... .......... .......... 16%  139M 0s
  4300K .......... .......... .......... .......... .......... 16%  126M 0s
  4350K .......... .......... .......... .......... .......... 16%  108M 0s
  4400K .......... .......... .......... .......... .......... 16%  141M 0s
  4450K .......... .......... .......... .......... .......... 16%  126M 0s
  4500K .......... .......... .......... .......... .......... 16%  127M 0s
  4550K .......... .......... .......... .......... .......... 17%  125M 0s
  4600K .......... .......... .......... .......... .......... 17%  127M 0s
  4650K .......... .......... .......... .......... .......... 17%  143M 0s
  4700K .......... .......... .......... .......... .......... 17%  143M 0s
  4750K .......... .......... .......... .......... .......... 17%  114M 0s
  4800K .......... .......... .......... .......... .......... 18%  145M 0s
  4850K .......... .......... .......... .......... .......... 18%  168M 0s
  4900K .......... .......... .......... .......... .......... 18%  114M 0s
  4950K .......... .......... .......... .......... .......... 18%  146M 0s
  5000K .......... .......... .......... .......... .......... 18%  160M 0s
  5050K .......... .......... .......... .......... .......... 19%  166M 0s
  5100K .......... .......... .......... .......... .......... 19%  145M 0s
  5150K .......... .......... .......... .......... .......... 19%  141M 0s
  5200K .......... .......... .......... .......... .......... 19%  158M 0s
  5250K .......... .......... .......... .......... .......... 19%  151M 0s
  5300K .......... .......... .......... .......... .......... 19%  171M 0s
  5350K .......... .......... .......... .......... .......... 20%  141M 0s
  5400K .......... .......... .......... .......... .......... 20%  130M 0s
  5450K .......... .......... .......... .......... .......... 20%  127M 0s
  5500K .......... .......... .......... .......... .......... 20%  124M 0s
  5550K .......... .......... .......... .......... .......... 20%  144M 0s
  5600K .......... .......... .......... .......... .......... 21%  141M 0s
  5650K .......... .......... .......... .......... .......... 21%  140M 0s
  5700K .......... .......... .......... .......... .......... 21%  134M 0s
  5750K .......... .......... .......... .......... .......... 21%  120M 0s
  5800K .......... .......... .......... .......... .......... 21%  137M 0s
  5850K .......... .......... .......... .......... .......... 22%  142M 0s
  5900K .......... .......... .......... .......... .......... 22%  130M 0s
  5950K .......... .......... .......... .......... .......... 22%  150M 0s
  6000K .......... .......... .......... .......... .......... 22%  163M 0s
  6050K .......... .......... .......... .......... .......... 22%  160M 0s
  6100K .......... .......... .......... .......... .......... 22%  114M 0s
  6150K .......... .......... .......... .......... .......... 23%  132M 0s
  6200K .......... .......... .......... .......... .......... 23%  130M 0s
  6250K .......... .......... .......... .......... .......... 23%  150M 0s
  6300K .......... .......... .......... .......... .......... 23%  122M 0s
  6350K .......... .......... .......... .......... .......... 23%  157M 0s
  6400K .......... .......... .......... .......... .......... 24%  155M 0s
  6450K .......... .......... .......... .......... .......... 24%  148M 0s
  6500K .......... .......... .......... .......... .......... 24%  152M 0s
  6550K .......... .......... .......... .......... .......... 24%  149M 0s
  6600K .......... .......... .......... .......... .......... 24%  168M 0s
  6650K .......... .......... .......... .......... .......... 25%  146M 0s
  6700K .......... .......... .......... .......... .......... 25%  172M 0s
  6750K .......... .......... .......... .......... .......... 25%  153M 0s
  6800K .......... .......... .......... .......... .......... 25%  125M 0s
  6850K .......... .......... .......... .......... .......... 25%  155M 0s
  6900K .......... .......... .......... .......... .......... 25%  156M 0s
  6950K .......... .......... .......... .......... .......... 26%  118M 0s
  7000K .......... .......... .......... .......... .......... 26%  140M 0s
  7050K .......... .......... .......... .......... .......... 26%  161M 0s
  7100K .......... .......... .......... .......... .......... 26%  141M 0s
  7150K .......... .......... .......... .......... .......... 26%  123M 0s
  7200K .......... .......... .......... .......... .......... 27%  157M 0s
  7250K .......... .......... .......... .......... .......... 27%  138M 0s
  7300K .......... .......... .......... .......... .......... 27%  141M 0s
  7350K .......... .......... .......... .......... .......... 27%  158M 0s
  7400K .......... .......... .......... .......... .......... 27%  130M 0s
  7450K .......... .......... .......... .......... .......... 28%  136M 0s
  7500K .......... .......... .......... .......... .......... 28%  130M 0s
  7550K .......... .......... .......... .......... .......... 28%  139M 0s
  7600K .......... .......... .......... .......... .......... 28%  142M 0s
  7650K .......... .......... .......... .......... .......... 28%  143M 0s
  7700K .......... .......... .......... .......... .......... 28%  171M 0s
  7750K .......... .......... .......... .......... .......... 29%  135M 0s
  7800K .......... .......... .......... .......... .......... 29%  149M 0s
  7850K .......... .......... .......... .......... .......... 29%  134M 0s
  7900K .......... .......... .......... .......... .......... 29%  148M 0s
  7950K .......... .......... .......... .......... .......... 29%  132M 0s
  8000K .......... .......... .......... .......... .......... 30%  145M 0s
  8050K .......... .......... .......... .......... .......... 30%  136M 0s
  8100K .......... .......... .......... .......... .......... 30%  156M 0s
  8150K .......... .......... .......... .......... .......... 30%  157M 0s
  8200K .......... .......... .......... .......... .......... 30%  163M 0s
  8250K .......... .......... .......... .......... .......... 31%  132M 0s
  8300K .......... .......... .......... .......... .......... 31%  148M 0s
  8350K .......... .......... .......... .......... .......... 31%  154M 0s
  8400K .......... .......... .......... .......... .......... 31%  155M 0s
  8450K .......... .......... .......... .......... .......... 31%  123M 0s
  8500K .......... .......... .......... .......... .......... 31%  132M 0s
  8550K .......... .......... .......... .......... .......... 32%  159M 0s
  8600K .......... .......... .......... .......... .......... 32%  173M 0s
  8650K .......... .......... .......... .......... .......... 32%  134M 0s
  8700K .......... .......... .......... .......... .......... 32%  134M 0s
  8750K .......... .......... .......... .......... .......... 32%  166M 0s
  8800K .......... .......... .......... .......... .......... 33%  171M 0s
  8850K .......... .......... .......... .......... .......... 33%  141M 0s
  8900K .......... .......... .......... .......... .......... 33%  178M 0s
  8950K .......... .......... .......... .......... .......... 33%  148M 0s
  9000K .......... .......... .......... .......... .......... 33%  122M 0s
  9050K .......... .......... .......... .......... .......... 33%  129M 0s
  9100K .......... .......... .......... .......... .......... 34%  158M 0s
  9150K .......... .......... .......... .......... .......... 34%  144M 0s
  9200K .......... .......... .......... .......... .......... 34%  144M 0s
  9250K .......... .......... .......... .......... .......... 34%  161M 0s
  9300K .......... .......... .......... .......... .......... 34%  129M 0s
  9350K .......... .......... .......... .......... .......... 35%  174M 0s
  9400K .......... .......... .......... .......... .......... 35%  141M 0s
  9450K .......... .......... .......... .......... .......... 35%  151M 0s
  9500K .......... .......... .......... .......... .......... 35%  141M 0s
  9550K .......... .......... .......... .......... .......... 35%  120M 0s
  9600K .......... .......... .......... .......... .......... 36%  151M 0s
  9650K .......... .......... .......... .......... .......... 36%  163M 0s
  9700K .......... .......... .......... .......... .......... 36%  152M 0s
  9750K .......... .......... .......... .......... .......... 36%  129M 0s
  9800K .......... .......... .......... .......... .......... 36%  143M 0s
  9850K .......... .......... .......... .......... .......... 36%  164M 0s
  9900K .......... .......... .......... .......... .......... 37%  152M 0s
  9950K .......... .......... .......... .......... .......... 37%  161M 0s
 10000K .......... .......... .......... .......... .......... 37%  124M 0s
 10050K .......... .......... .......... .......... .......... 37%  113M 0s
 10100K .......... .......... .......... .......... .......... 37%  174M 0s
 10150K .......... .......... .......... .......... .......... 38%  138M 0s
 10200K .......... .......... .......... .......... .......... 38%  139M 0s
 10250K .......... .......... .......... .......... .......... 38%  163M 0s
 10300K .......... .......... .......... .......... .......... 38%  171M 0s
 10350K .......... .......... .......... .......... .......... 38%  143M 0s
 10400K .......... .......... .......... .......... .......... 39%  160M 0s
 10450K .......... .......... .......... .......... .......... 39%  162M 0s
 10500K .......... .......... .......... .......... .......... 39%  121M 0s
 10550K .......... .......... .......... .......... .......... 39%  130M 0s
 10600K .......... .......... .......... .......... .......... 39%  165M 0s
 10650K .......... .......... .......... .......... .......... 39%  147M 0s
 10700K .......... .......... .......... .......... .......... 40%  155M 0s
 10750K .......... .......... .......... .......... .......... 40%  127M 0s
 10800K .......... .......... .......... .......... .......... 40%  159M 0s
 10850K .......... .......... .......... .......... .......... 40%  156M 0s
 10900K .......... .......... .......... .......... .......... 40%  161M 0s
 10950K .......... .......... .......... .......... .......... 41%  127M 0s
 11000K .......... .......... .......... .......... .......... 41%  161M 0s
 11050K .......... .......... .......... .......... .......... 41%  164M 0s
 11100K .......... .......... .......... .......... .......... 41%  127M 0s
 11150K .......... .......... .......... .......... .......... 41%  130M 0s
 11200K .......... .......... .......... .......... .......... 42%  144M 0s
 11250K .......... .......... .......... .......... .......... 42%  179M 0s
 11300K .......... .......... .......... .......... .......... 42%  182M 0s
 11350K .......... .......... .......... .......... .......... 42%  167M 0s
 11400K .......... .......... .......... .......... .......... 42%  133M 0s
 11450K .......... .......... .......... .......... .......... 42%  171M 0s
 11500K .......... .......... .......... .......... .......... 43%  173M 0s
 11550K .......... .......... .......... .......... .......... 43%  162M 0s
 11600K .......... .......... .......... .......... .......... 43%  133M 0s
 11650K .......... .......... .......... .......... .......... 43%  150M 0s
 11700K .......... .......... .......... .......... .......... 43%  148M 0s
 11750K .......... .......... .......... .......... .......... 44%  155M 0s
 11800K .......... .......... .......... .......... .......... 44%  123M 0s
 11850K .......... .......... .......... .......... .......... 44%  155M 0s
 11900K .......... .......... .......... .......... .......... 44%  137M 0s
 11950K .......... .......... .......... .......... .......... 44%  155M 0s
 12000K .......... .......... .......... .......... .......... 45%  115M 0s
 12050K .......... .......... .......... .......... .......... 45%  154M 0s
 12100K .......... .......... .......... .......... .......... 45%  145M 0s
 12150K .......... .......... .......... .......... .......... 45%  120M 0s
 12200K .......... .......... .......... .......... .......... 45%  161M 0s
 12250K .......... .......... .......... .......... .......... 45%  161M 0s
 12300K .......... .......... .......... .......... .......... 46%  128M 0s
 12350K .......... .......... .......... .......... .......... 46%  155M 0s
 12400K .......... .......... .......... .......... .......... 46%  143M 0s
 12450K .......... .......... .......... .......... .......... 46%  165M 0s
 12500K .......... .......... .......... .......... .......... 46%  149M 0s
 12550K .......... .......... .......... .......... .......... 47%  159M 0s
 12600K .......... .......... .......... .......... .......... 47%  153M 0s
 12650K .......... .......... .......... .......... .......... 47%  132M 0s
 12700K .......... .......... .......... .......... .......... 47%  140M 0s
 12750K .......... .......... .......... .......... .......... 47%  150M 0s
 12800K .......... .......... .......... .......... .......... 48%  154M 0s

In [20]:
rdrsegmenter = py_vncorenlp.VnCoreNLP(annotators=["wseg"], save_dir='/kaggle/working/')

2024-04-24 15:28:37 INFO  WordSegmenter:24 - Loading Word Segmentation model

In [21]:
def preprocess_data(data_point):
    tokenized_input = ' '.join(rdrsegmenter.word_segment(' '.join([data_point['Contents'], data_point['input']])))

    model_input = tokenizer(tokenized_input, max_length=max_source_length, padding=False, truncation=True)

    # Tokenize targets with the `text_target` keyword argument
    tokenized_target = ' '.join(rdrsegmenter.word_segment(data_point['output']))
    labels = tokenizer(text_target=tokenized_target, max_length=max_target_length, padding=False, truncation=True)

    # If we are padding here, replace all tokenizer.pad_token_id in the labels by -100 when we want to ignore
    # padding in the loss.
    # if padding == "max_length" and data_args.ignore_pad_token_for_loss:
    #     labels["input_ids"] = [
    #         [(l if l != tokenizer.pad_token_id else -100) for l in label] for label in labels["input_ids"]
    #     ]

    model_input["labels"] = labels["input_ids"]
    return model_input

In [22]:
def create_prompt(data_point):
    article, summary = data_point["Contents"], data_point["Summary"]
#     article = unicodedata.normalize("utf8", article)
    article = re.sub(r'\s(\.)\s', ' ', article)
    
    summary = re.sub(r'([^a-zA-Z\s])?\n(\w+)', r'\1 \2', summary)
    summary = re.sub(r'\s(\.)', '.', summary)
    return article.strip(), summary.strip()


def generate_text(data_point):
    article, summary = create_prompt(data_point)
    return generate_training_prompt(article, summary)

In [23]:
example_data_point = {
    "Contents": df.iloc[5]["Contents"],
    "Summary": df.iloc[5]["Summary"]
}


example = generate_text(example_data_point)
print(example)

<s>[INST]  <<SYS>>


Bạn là một trợ lí Tiếng Việt nhiệt tình và trung thực. Hãy luôn trả lời một cách hữu ích nhất có thể, đồng thời giữ an toàn.
Câu trả lời của bạn không nên chứa bất kỳ nội dung gây hại, phân biệt chủng tộc, phân biệt giới tính, độc hại, nguy hiểm hoặc bất hợp pháp nào.
Hãy đảm bảo rằng các câu trả lời của bạn không có thiên kiến xã hội và mang tính tích cực. Nếu một câu hỏi không có ý nghĩa hoặc không hợp lý về
mặt thông tin, hãy giải thích tại sao thay vì trả lời một điều gì đó không chính xác. Nếu bạn không biết câu trả lời cho một câu hỏi, hãy trẳ lời
là bạn không biết và vui lòng không chia sẻ thông tin sai lệch.
Dưới đây là một tin tức. Bạn hãy viết một đoạn tóm tắt tin tức trên trong khoảng 100 từ. Hãy tóm tắt nội dung chính, quan trọng của tin tức đó,
đồng thời đoạn tóm tắt phải được viết lại rõ ràng, thông tin được viết lại hợp lý.

<</SYS>>


Những ngày qua, đất khu đô thị Thanh Hà Cienco đang có hiện tượng các cò đất thổi giá khi có thông tin chủ đầu tư thông báo khởi công công trình nhà thấp tầng tại lô B1.1. Theo đó, các sàn môi giới đang truyền tay nhau văn bản của Công ty CP Phát triển địa ốc Cienco5 - chủ đầu tư dự án về việc thông báo khởi công xây dựng công trình nhà ở thấp tầng dự án khu đô thị Thanh Hà Cienco5. Cụ thể, thông báo được gửi đến UBND quận Hà Đông, UBND huyện Thanh Oai với nội dung: Ngày 16.5.2022, chủ đầu tư khởi công xây dựng công trình nhà ở thấp tầng khu B1.1 thuộc dự án khu đô thị Thanh Hà Cienco 5.   Ngay sau khi có thông tin về việc các cò đất thổi giá tại khu đô thị Thanh Hà Cienco5, cơ quan chức năng Hà Nội đã phải ra văn bản yêu cầu dừng mọi hoạt động xây dựng tại dự án. Theo đó, UBND quận Hà Đông vừa có Công văn khẩn số 1052 yêu cầu phòng Quản lý đô thị chủ trì, phối hợp Đội Quản lý trật tự xây dựng đô thị, UBND các phường Phú Lương, Kiến Hưng rà soát hồ sơ pháp lý, điều kiện khởi công công trình tại dự án khu đô thị Thanh Hà Cienco5. “Chỉ cho phép chủ đầu tư khởi công công trình khi hoàn thiện đầy đủ các thủ tục thẩm định, phê duyệt dự án, thiết kế theo đúng trình tự, quy định của pháp luật”, văn bản của UBND quận Hà Đông nêu rõ. Trong khi đó, UBND huyện Thanh Oai cho biết, UBND TP Hà Nội, Sở Xây dựng Hà Nội đã có văn bản yêu cầu khắc phục những thiếu sót, khuyết điểm về trình tự, thủ tục, quy hoạch, trật tự xây dựng, đất đai nhưng đến nay Công ty CP phát triển địa ốc Cienco 5 chưa khắc phục xong. Đồng thời, UBND huyện Thanh Oai yêu cầu chủ đầu tư tiếp tục dừng mọi hoạt động thi công xây dựng tại khu đô thị Thanh Hà - Cienco 5 theo chỉ đạo của UBND TP Hà Nội cho đến khi có văn bản chỉ đạo của cấp có thẩm quyền về việc cho phép tiếp tục xây dựng.   UBND huyện Thanh Oai giao Đội Quản lý trật tự xây dựng và đô thị huyện, UBND xã Cự Khê thường xuyên kiểm tra, giám sát việc thực hiện đình chỉ mọi hoạt động xây dựng tại khu đô thị Thanh Hà - Cienco 5... Ghi nhận của PV Lao Động bên trong khu đô thị Thanh Hà Cienco 5 (Hà Nội) cho thấy, ngoài những tòa chung cư, một ít khu biệt thự đã đưa vào sử dụng thì phần lớn đất bỏ hoang cho cỏ mọc, làm nơi chăn thả trâu bò của người dân. Nhiều hộ dân còn tận dụng khu đất trống để trồng rau, cây ăn quả. Trong vai một khách hàng, PV được nhiều môi giới cho biết, hiện giá các lô biệt thự, liền kề tại đây giao động từ 60-65 triệu đồng/m2. Không chỉ tại vị trí khu đất có thông báo xây dựng công trình tăng giá mà các lô tại ví trí khác cũng tăng giá ăn theo. Đơn cử những lô biệt thự diện tích 200m2 đang có giá dao động từ 50-60 triệu đồng/m2, trong khi đó lô có diện tích lớn trên 300m2, giá giao động từ 46-47 triệu đồng/m2. Mức giá này cao hơn so với thời điểm trước khi có thông tin chủ đầu khởi công khu nhà thấp tầng từ 4-5 giá. Thậm chí, có lô tăng đến 10 giá nhưng không có hàng để bán.[/INST]

### Response:
Khu đô thị Thanh Hà Cienco 5 (thuộc quận Hà Đông và huyện Thanh Oai, Hà Nội) sau nhiều năm nằm bất động do dự án vướng sai phạm và dừng mọi hoạt động xây dựng thì những ngày gần đây bỗng xuất hiện cơn “sóng” đất.</s>

In [24]:
MODEL_NAME = "Viet-Mistral/Vistral-7B-Chat"
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

In [25]:
def create_model_and_tokenizer():
    nf4_config = BitsAndBytesConfig(
        load_in_4bit = True,
        bnb_4bit_quant_type = "nf4",
        bnb_4bit_use_double_quant = True,
        bnb_4bit_compute_dtype = torch.bfloat16
    )


    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        device_map='auto',
        quantization_config=nf4_config,
        use_cache=False
    )
    
    model.config.use_cache = False
    
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    return model, tokenizer

In [26]:
import os

os.environ["WANDB_PROJECT"] = "vietnamese-news-summarization"
os.environ["WANDB_LOG_MODEL"] = "checkpoint"

In [ ]:
import wandb

wandb.login()
wandb.init()

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: vu25ck28. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.6
wandb: Run data is saved locally in /kaggle/working/wandb/run-20240424_152839-8h0k61vj
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fast-night-2
wandb: ⭐️ View project at https://wandb.ai/vu25ck28/vietnamese-news-summarization
wandb: 🚀 View run at https://wandb.ai/vu25ck28/vietnamese-news-summarization/runs/8h0k61vj

In [ ]:
from huggingface_hub import login

login()

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful

In [29]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

model, tokenizer = create_model_and_tokenizer()

config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/10.0G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/4.59G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.52k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/597k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.15M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/169 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

In [30]:
if torch.cuda.device_count() > 1: # If more than 1 GPU
    model.is_parallelizable = True
    model.model_parallel = True
model.config.quantization_config.to_dict()

{'quant_method': <QuantizationMethod.BITS_AND_BYTES: 'bitsandbytes'>,
 '_load_in_8bit': False,
 '_load_in_4bit': True,
 'llm_int8_threshold': 6.0,
 'llm_int8_skip_modules': None,
 'llm_int8_enable_fp32_cpu_offload': False,
 'llm_int8_has_fp16_weight': False,
 'bnb_4bit_quant_type': 'nf4',
 'bnb_4bit_use_double_quant': True,
 'bnb_4bit_compute_dtype': 'bfloat16',
 'bnb_4bit_quant_storage': 'uint8',
 'load_in_4bit': True,
 'load_in_8bit': False}

In [31]:
# Set LoRA configuration
peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
        "lm_head",
    ],
    bias="none",
    task_type="CAUSAL_LM",
)

In [32]:
from peft import *

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

In [33]:
##############################
# TrainingArguments parameters
##############################

# Output directory where the model predictions and checkpoints will be stored
output_dir = "vietnamese-news-summarization-vistral-7b-finetuned"

# Number of training epochs
# num_train_epochs = 5

# Enable fp16/bf16 training (set bf16 to True with an A100)
fp16 = False
bf16 = True

In [34]:
training_arguments = TrainingArguments(
    per_device_train_batch_size = 4,
    logging_steps = 10,
    learning_rate = 2e-4,
    max_steps = 100, # the total number of training steps to perform
    num_train_epochs = 3,
    evaluation_strategy="steps",
    eval_steps=20,
    save_steps=20,
    warmup_steps = 0.03,
    save_strategy="steps",
    group_by_length = True,
    output_dir = output_dir,
    report_to="wandb",  # Set report_to here
    run_name='finetune-vistral-7b',
    save_safetensors=True,
    lr_scheduler_type = 'constant',
    load_best_model_at_end = True,
    push_to_hub = True,
    push_to_hub_model_id = "vietnamese-news-summarization-vistral-7b",
    push_to_hub_token=access_token_write
)

In [35]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=validation_dataset,
    peft_config=peft_config,
    formatting_func=generate_text,
    max_seq_length=300,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=True
)

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

max_steps is given, it will override any value given in num_train_epochs

In [36]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

with torch.no_grad():
    torch.cuda.empty_cache()

# Fine-tune your model
trainer.train()

wandb: Adding directory to artifact (./vietnamese-news-summarization-vistral-7b-finetuned/checkpoint-20)... Done. 15.6s
wandb: Adding directory to artifact (./vietnamese-news-summarization-vistral-7b-finetuned/checkpoint-40)... Done. 19.7s
wandb: Adding directory to artifact (./vietnamese-news-summarization-vistral-7b-finetuned/checkpoint-60)... Done. 17.7s
wandb: Adding directory to artifact (./vietnamese-news-summarization-vistral-7b-finetuned/checkpoint-80)... Done. 21.2s
wandb: Adding directory to artifact (./vietnamese-news-summarization-vistral-7b-finetuned/checkpoint-100)... Done. 25.3s
max_steps is given, it will override any value given in num_train_epochs

TrainOutput(global_step=100, training_loss=1.3397535133361815, metrics={'train_runtime': 12863.9065, 'train_samples_per_second': 0.031, 'train_steps_per_second': 0.008, 'total_flos': 5261210956800000.0, 'train_loss': 1.3397535133361815, 'epoch': 0.02976190476190476})

In [37]:
trainer.push_to_hub()

CommitInfo(commit_url='https://huggingface.co/anhvu2501/vietnamese-news-summarization-vistral-7b/commit/33cd19fb8af1eeae5591916f1fe843db74a637b0', commit_message='End of training', commit_description='', oid='33cd19fb8af1eeae5591916f1fe843db74a637b0', pr_url=None, pr_revision=None, pr_num=None)

In [38]:
trainer.save_model("vietnamese-news-summarization-finetuned-vistral-7b")

### Inference

In [39]:
gc.collect()
torch.cuda.empty_cache()

In [40]:
artifact = wandb.Api().artifact("vu25ck28/vietnamese-news-summarization/checkpoint-robust-night-1:v0", type='model')
artifact.download()

wandb: Downloading large artifact checkpoint-robust-night-1:v0, 2553.69MB. 13 files...
wandb:   13 of 13 files downloaded.
Done. 0:0:22.7

'/kaggle/working/artifacts/checkpoint-robust-night-1:v0'

In [41]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

nf4_config = BitsAndBytesConfig(
        load_in_4bit = True,
        bnb_4bit_quant_type = "nf4",
        bnb_4bit_use_double_quant = True,
        bnb_4bit_compute_dtype = torch.bfloat16
    )

inf_model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        device_map='auto',
        quantization_config=nf4_config,
        use_cache=False
    )

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [42]:
model = PeftModel.from_pretrained(inf_model, "/kaggle/working/artifacts/checkpoint-robust-night-1:v0")

In [43]:
test_dataset['Contents'][1]

'Thế hệ “không xu dính túi” đang thay đổi ngành bất động sản Tập 5 series talk show "NGƯỜI TIÊN PHONG" mới lên sóng với chủ đề "Gen Z: Phá vỡ giới hạn - Đột phá tiên phong" đã vẽ nên chân dung thế hệ Gen Z điển hình - những người đang buộc thị trường phải thay đổi theo hướng tích cực hơn. Vân và Thái là đại diện cho thế hệ những người trẻ thành công sớm. Sinh ra trong thời kỳ đất nước hội nhập, tiếp thu những công nghệ mới, tư duy về tài sản cùng phong cách đầu tư xuống tiền của Gen Z đã táo bạo hơn trước rất nhiều, ngay cả trong lĩnh vực đòi hỏi sự đầu tư, tích lũy và chuẩn bị trong một thời gian dài đối với các thế hệ trước như mua nhà. Ngôi nhà chính là minh chứng cho khả năng kiếm tiền và là một trong những thước đo cho sự thành công của giới trẻ toàn cầu. Thay vì chọn nhà là nơi để ở như nếp nghĩ của các thế hệ trước, Gen Z coi nhà là một khoản đầu tư. Hai khách mời đồng tình rằng, với nhà ở, Gen Z không chỉ mưu cầu những khoản lãi về tiền bạc, mà họ còn tìm kiếm trải nghiệm, sức khỏe, chất lượng sống. Sự dịch chuyển nhu cầu của tập khách hàng mới đầy tiềm năng này cũng đặt ra sự thay đổi của giới BĐS, cần thích nghi để đưa ra các sản phẩm phù hợp cho họ. Cuộc sống "Smart & Resort Living" của Gen Z Theo một khảo sát từ Vinhomes, trong 10.000 khách hàng đầu tiên “xuống tiền” mua nhà tại đại đô thị Vinhomes Smart City, có tới 15% các bạn trẻ mới chỉ trên 25 tuổi. Đây cũng là quy luật chung trên toàn thế giới. Khảo sát từ Homes.com, một nền tảng BĐS có tiếng của Mỹ cho biết: 85,8% Gen Z có kế hoạch mua nhà trước tuổi 35; trong đó 48,1% kỳ vọng có nhà riêng trong tầm 25-29 tuổi. Cần một không gian riêng, lãi suất thấp và ảnh hưởng của đại dịch COVID-19 là ba lý do giải thích tại sao gen Z chọn thời điểm hiện tại là thích hợp nhất để mua nhà riêng.     “Khi hỏi một người Gen Y (8X đến đầu 9X) câu hỏi tại sao bạn lại chuyển ra khỏi nhà thì câu trả lời sẽ là ‘Tôi không muốn bị kìm kẹp nữa’. Còn với Gen Z thì việc ra khỏi nhà chỉ đơn giản là các bạn muốn có một không gian dành riêng cho bản thân. Vì thế, nhà của Gen Z có nhiều không gian như thiền, cây xanh, đá năng lượng...”, Giám đốc Startup Grind Việt Nam chia sẻ. CEO Nguyễn Quang Thái cho rằng, không gian một ngôi nhà bây giờ không chỉ phục vụ việc để ở mà nó cần mang yếu tố cá nhân hóa cho từng người, đảm bảo sự văn minh, hiện đại và chuẩn phong cách sống “smart living” - sự thông minh trong cách sống, tạo ra sự độc bản của mỗi người. “Tôi làm để sống chứ tôi không sống để làm - đây là một tư tưởng rất Gen Z. Khi mình có được sự cân bằng thì cuộc sống mình tốt lên, công việc mình tốt lên”, CEO Thái lý giải nhu cầu "resort living" của Gen Z xuất phát từ áp lực cuộc sống, từ deadline mà họ gặp phải mỗi ngày. Đó cũng là lý do sao Gen Z có xu hướng lựa chọn những “đại đô thị 15 phút” - tức mọi nhu cầu của họ từ ăn uống, học tập, nghỉ dưỡng, mua sắm, khám chữa bệnh… đều có thể được đáp ứng đầy đủ chỉ với vài bước chân.  “Cộng đồng thông minh chính là sự lựa chọn của thế hệ trẻ. Như với Vinhomes, nhiều gia đình trẻ có tri thức, có tầm nhìn, họ mới nhắm đến Vinhomes Smart City, cộng đồng công dân toàn cầu đến từ 20 quốc gia và vùng lãnh thổ, nơi tốt nhất cho mọi thành viên trong gia đình phát triển trí tuệ, thể chất”, bà Phương cho biết. Xã hội gọi Gen Z là “những đứa trẻ khác biệt”, nhưng chính những “đứa trẻ” này đang nắm trong tay chìa khoá của sự thay đổi, từ dòng tiền, công nghệ cho đến chất lượng dịch vụ. Các nghiên cứu đều đồng tình rằng, đây là thế hệ tiên phong, vì Gen Z đang lớn lên từ việc phá bỏ định kiến và quy luật cũ, tạo ra giá trị mới cho xã hội. Gen Z chính là tương lai của nền kinh tế.'

In [44]:
from tqdm import tqdm

In [45]:
prompt="""<s>[INST]  <<SYS>>


Bạn là một trợ lí Tiếng Việt nhiệt tình và trung thực. Hãy luôn trả lời một cách hữu ích nhất có thể, đồng thời giữ an toàn.
Câu trả lời của bạn không nên chứa bất kỳ nội dung gây hại, phân biệt chủng tộc, phân biệt giới tính, độc hại, nguy hiểm hoặc bất hợp pháp nào. 
Hãy đảm bảo rằng các câu trả lời của bạn không có thiên kiến xã hội và mang tính tích cực. Nếu một câu hỏi không có ý nghĩa hoặc không hợp lý về 
mặt thông tin, hãy giải thích tại sao thay vì trả lời một điều gì đó không chính xác. Nếu bạn không biết câu trả lời cho một câu hỏi, hãy trẳ lời 
là bạn không biết và vui lòng không chia sẻ thông tin sai lệch. 
Dưới đây là một tin tức. Bạn hãy viết một đoạn tóm tắt tin tức trên trong khoảng 100 từ. Hãy tóm tắt nội dung chính, quan trọng của tin tức đó, 
đồng thời đoạn tóm tắt phải được viết lại rõ ràng, thông tin được viết lại hợp lý. 
 
<</SYS>> 

Thế hệ “không xu dính túi” đang thay đổi ngành bất động sản Tập 5 series talk show "NGƯỜI TIÊN PHONG" mới lên sóng với chủ đề "Gen Z: Phá vỡ giới hạn - 
Đột phá tiên phong" đã vẽ nên chân dung thế hệ Gen Z điển hình - những người đang buộc thị trường phải thay đổi theo hướng tích cực hơn. Vân và Thái 
là đại diện cho thế hệ những người trẻ thành công sớm. Sinh ra trong thời kỳ đất nước hội nhập, tiếp thu những công nghệ mới, tư duy về tài sản cùng 
phong cách đầu tư xuống tiền của Gen Z đã táo bạo hơn trước rất nhiều, ngay cả trong lĩnh vực đòi hỏi sự đầu tư, tích lũy và chuẩn bị trong một 
thời gian dài đối với các thế hệ trước như mua nhà. Ngôi nhà chính là minh chứng cho khả năng kiếm tiền và là một trong những thước đo cho sự 
thành công của giới trẻ toàn cầu. Thay vì chọn nhà là nơi để ở như nếp nghĩ của các thế hệ trước, Gen Z coi nhà là một khoản đầu tư. Hai khách mời 
đồng tình rằng, với nhà ở, Gen Z không chỉ mưu cầu những khoản lãi về tiền bạc, mà họ còn tìm kiếm trải nghiệm, sức khỏe, chất lượng sống. 

### Response:
"""
device = "cuda" if torch.cuda.is_available() else "cpu"
model_input = tokenizer(prompt, return_tensors="pt").to(device)


_ = model.eval()
with torch.no_grad():
    out = model.generate(**model_input, max_new_tokens=200)

print(tokenizer.decode(out[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

[INST]   <<SYS>>


Bạn là một trợ lí Tiếng Việt nhiệt tình và trung thực. Hãy luôn trả lời một cách hữu ích nhất có thể, đồng thời giữ an toàn.
Câu trả lời của bạn không nên chứa bất kỳ nội dung gây hại, phân biệt chủng tộc, phân biệt giới tính, độc hại, nguy hiểm hoặc bất hợp pháp nào.
Hãy đảm bảo rằng các câu trả lời của bạn không có thiên kiến xã hội và mang tính tích cực. Nếu một câu hỏi không có ý nghĩa hoặc không hợp lý về
mặt thông tin, hãy giải thích tại sao thay vì trả lời một điều gì đó không chính xác. Nếu bạn không biết câu trả lời cho một câu hỏi, hãy trẳ lời
là bạn không biết và vui lòng không chia sẻ thông tin sai lệch.
Dưới đây là một tin tức. Bạn hãy viết một đoạn tóm tắt tin tức trên trong khoảng 100 từ. Hãy tóm tắt nội dung chính, quan trọng của tin tức đó,
đồng thời đoạn tóm tắt phải được viết lại rõ ràng, thông tin được viết lại hợp lý.

<</SYS>>

Thế hệ “không xu dính túi” đang thay đổi ngành bất động sản Tập 5 series talk show "NGƯỜI TIÊN PHONG" mới lên sóng với chủ đề "Gen Z: Phá vỡ giới hạn -
Đột phá tiên phong" đã vẽ nên chân dung thế hệ Gen Z điển hình - những người đang buộc thị trường phải thay đổi theo hướng tích cực hơn. Vân và Thái
là đại diện cho thế hệ những người trẻ thành công sớm. Sinh ra trong thời kỳ đất nước hội nhập, tiếp thu những công nghệ mới, tư duy về tài sản cùng
phong cách đầu tư xuống tiền của Gen Z đã táo bạo hơn trước rất nhiều, ngay cả trong lĩnh vực đòi hỏi sự đầu tư, tích lũy và chuẩn bị trong một
thời gian dài đối với các thế hệ trước như mua nhà. Ngôi nhà chính là minh chứng cho khả năng kiếm tiền và là một trong những thước đo cho sự
thành công của giới trẻ toàn cầu. Thay vì chọn nhà là nơi để ở như nếp nghĩ của các thế hệ trước, Gen Z coi nhà là một khoản đầu tư. Hai khách mời
đồng tình rằng, với nhà ở, Gen Z không chỉ mưu cầu những khoản lãi về tiền bạc, mà họ còn tìm kiếm trải nghiệm, sức khỏe, chất lượng sống.

### Response:

Tập 5 của series talk show "NGƯỜI TIÊN PHONG" đã khám phá cách thế hệ Gen Z đang thay đổi ngành bất động sản bằng cách đầu tư vào nhà ở như một khoản đầu tư. Hai khách mời, Vân và Thái, đại diện cho thế hệ những người trẻ thành công sớm, đã thảo luận về cách tiếp cận của họ đối với việc mua nhà. Thay vì chỉ là một nơi để ở, Gen Z coi nhà là một khoản đầu tư, tìm kiếm trải nghiệm, sức khỏe và chất lượng sống. Sự thay đổi này trong tư duy đã buộc thị trường phải thay đổi theo hướng tích cực hơn.